import type { Metadata } from "next";
import "./globals.css";
import { IChildren } from "../interfaces/IChildren";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "app-libreria",
  description: "Generated by nextjs",
};

export default function RootLayout({ children }: IChildren,) {
  return (
    <html className="h-full" lang="en">
      <body className="h-full">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}